// flow-typed signature: a84a4cf6e70f97b7cda1d88816d68022
// flow-typed version: <<STUB>>/docz-theme-default_v^0.5.8/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'docz-theme-default'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'docz-theme-default' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'docz-theme-default/dist/index' {
  declare module.exports: any;
}

declare module 'docz-theme-default/dist/index.m' {
  declare module.exports: any;
}

declare module 'docz-theme-default/dist/index.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'docz-theme-default/dist/index.js' {
  declare module.exports: $Exports<'docz-theme-default/dist/index'>;
}
declare module 'docz-theme-default/dist/index.m.js' {
  declare module.exports: $Exports<'docz-theme-default/dist/index.m'>;
}
declare module 'docz-theme-default/dist/index.umd.js' {
  declare module.exports: $Exports<'docz-theme-default/dist/index.umd'>;
}
